version: '3.9'

services:
  server:
    build: ./backend/
    volumes:
      - ./backend/:/usr/src/app/
    environment: 
      PORT: 8085
    ports:
      - 8085:8085
      
  web:
    # needs this otherwise react app stops immediately
    # https://github.com/facebook/create-react-app/issues/8688
    stdin_open: true

    build: ./frontend/

    # causing npm to fail as it does not find package.json
    # only side-effect is you would need to rebuild the image for changes to show
    # mounting worked previously, but couldnt recreate later
    # volumes:
    #   - ./frontend:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - server
